BEGIN;

CREATE TABLE IF NOT EXISTS breakers (
    "id" SERIAL PRIMARY KEY,
    "snils" VARCHAR(11) NOT NULL,
    "checked" BOOLEAN NOT NULL,
    "datetime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;